// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Account struct {
	ID              int32
	Username        string
	Password        string
	Email           string
	Address         string
	Balance         float64
	IsAdmin         bool
	UserTag         sql.NullString
	UserPhoneNumber int64
}

type Food struct {
	FoodID      int32
	FoodName    string
	Price       float64
	FoodType    string
	Picture     sql.NullString
	LongRange   bool
	Description string
	Info        sql.NullString
	Ingredients string
	TimeNeeded  int32
}

type Item struct {
	ItemID   int32
	OrderID  int32
	FoodID   int32
	Quantity int32
	Rating   sql.NullInt32
}

type Order struct {
	OrderID         int32
	UserID          int32
	OrderInfo       string
	Feedback        sql.NullString
	OrderTime       sql.NullTime
	EstimatedTime   time.Time
	IsDone          bool
	IsRanged        bool
	DeliveryAddress sql.NullString
	Deleted         bool
	IsPaid          bool
}

type Tag struct {
	Tag      string
	FoodName string
}
