// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Account struct {
	ID              int32
	Username        string
	Password        string
	Email           string
	Address         string
	UserTag         sql.NullString
	UserPhoneNumber int64
}

type Food struct {
	FoodID      int32
	FoodName    string
	FoodTag     string
	Price       float64
	Info        sql.NullString
	Ingredients string
	TimeNeeded  sql.NullString
}

type Item struct {
	ItemID   int32
	OrderID  int32
	FoodID   int32
	Quantity int32
}

type Order struct {
	OrderID   int32
	UserID    int32
	OrderInfo string
	Rating    sql.NullInt32
	Feedback  sql.NullString
	OrderTime sql.NullTime
	IsDone    bool
	IsRanged  bool
	Deleted   bool
}
